runtime: nodejs16

instance_class: B1
service: bi-model-development
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /app(.*)
  static_files: public/index.html
  upload: public/index.html

- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /assets
  static_dir: public/assets